export const courses = [
  {
    name: "Excel for beginners",
    url: "https://www.youtube.com/watch?v=Vl0H-qTclOg",
    thumbnail: "http://i3.ytimg.com/vi/Vl0H-qTclOg/hqdefault.jpg",
  },
  {
    name: "Intro in Kubernetes",
    url: "https://www.youtube.com/watch?v=s_o8dwzRlu4",
    thumbnail: "http://i3.ytimg.com/vi/s_o8dwzRlu4/hqdefault.jpg",
  },
  {
    name: "Statistics",
    url: "https://www.youtube.com/watch?v=xxpc-HPKN28",
    thumbnail: "http://i3.ytimg.com/vi/xxpc-HPKN28/hqdefault.jpg",
  },
  {
    name: "Prisma ORM",
    url: "https://www.youtube.com/watch?v=mU8-nKwfw4Y",
    thumbnail: "http://i3.ytimg.com/vi/mU8-nKwfw4Y/hqdefault.jpg",
  },
  {
    name: "Nextjs Crash course",
    url: "https://www.youtube.com/watch?v=6fNy0iD3hsk",
    thumbnail: "http://i3.ytimg.com/vi/6fNy0iD3hsk/hqdefault.jpg",
  },
  {
    name: "Chackra UI",
    url: "https://www.youtube.com/watch?v=s-bIsz-NR3c",
    thumbnail: "http://i3.ytimg.com/vi/s-bIsz-NR3c/hqdefault.jpg",
  },
  {
    name: "Modern Fullstack",
    url: "https://www.youtube.com/watch?v=PKy2lYEnhgs",
    thumbnail: "http://i3.ytimg.com/vi/PKy2lYEnhgs/hqdefault.jpg",
  },
  {
    name: "Conventional commits",
    url: "https://www.youtube.com/watch?v=lwGcnDgwmFc",
    thumbnail: " http://i3.ytimg.com/vi/lwGcnDgwmFc/hqdefault.jpg",
  },
];

export const skills = [
  { name: "cloud" },
  { name: "containers" },
  { name: "coding" },
  { name: "computer" },
  { name: "css" },
  { name: "design" },
  { name: "excel" },
  { name: "html" },
  { name: "javascript" },
  { name: "kubernetes" },
  { name: "math" },
  { name: "measure" },
  { name: "nextjs" },
  { name: "office" },
  { name: "organization" },
  { name: "ORM" },
  { name: "Prisma" },
  { name: "sql" },
  { name: "statistcs" },
  { name: "typescript" },
  { name: "UI" },
  { name: "scripting" },
  { name: "git" },
  { name: "calculations" },
];

export const coursesSkills = [
  { courseId: 1, skillId: 7 },
  { courseId: 1, skillId: 14 },
  { courseId: 1, skillId: 15 },
  { courseId: 1, skillId: 4 },
  { courseId: 2, skillId: 4 },
  { courseId: 2, skillId: 1 },
  { courseId: 2, skillId: 10 },
  { courseId: 2, skillId: 2 },
  { courseId: 3, skillId: 11 },
  { courseId: 3, skillId: 19 },
  { courseId: 3, skillId: 24 },
  { courseId: 3, skillId: 12 },
  { courseId: 4, skillId: 4 },
  { courseId: 4, skillId: 16 },
  { courseId: 4, skillId: 18 },
  { courseId: 4, skillId: 9 },
  { courseId: 5, skillId: 9 },
  { courseId: 5, skillId: 4 },
  { courseId: 5, skillId: 13 },
  { courseId: 5, skillId: 3 },
  { courseId: 6, skillId: 21 },
  { courseId: 6, skillId: 5 },
  { courseId: 6, skillId: 6 },
  { courseId: 6, skillId: 8 },
  { courseId: 7, skillId: 21 },
  { courseId: 7, skillId: 20 },
  { courseId: 7, skillId: 5 },
  { courseId: 7, skillId: 8 },
  { courseId: 8, skillId: 23 },
  { courseId: 8, skillId: 3 },
  { courseId: 8, skillId: 4 },
  { courseId: 8, skillId: 22 },
];
